global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'SimpleLoadbalancers'
    scrape_interval: 5s
    static_configs:
      - targets: ['app1:8080','app2:8080']
        labels:
          job: 'simple-loadbalancer'

  - job_name: 'haproxy'
    scrape_interval: 5s
    static_configs:
      - targets: ['haproxy:8404']
        labels:
          job: 'haproxy'

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
