{
 "title": "SimpleLoadbalancer Metric",
 "tags": [ "metric" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(service_http_request_count_total, job)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values(service_http_request_count_total{endpoint!~\"/metrics\", job=~\"$job\"}, endpoint)"
    }
   },
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values(service_http_request_count_total, method)"
    }
   },
   {
    "name": "status",
    "label": "Status",
    "query": {
     "query": "label_values(service_http_request_count_total, status)"
    }
   },
   { "name": "quantile", "label": "Quantile", "query": "0.95,0.75,0.25" }
  ]
 },
 "panels": [
  {
   "title": "Service Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_uptime{job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Service last updated",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - service_uptime{job=~\"$job\"}) * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum (rate(service_http_request_count_total{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$__interval])) by (endpoint,status,instance)",
     "legendFormat": "{{status}}-{{endpoint}}  [{{instance}}] "
    }
   ]
  },
  {
   "title": "Requests QPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(service_http_request_count_total{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])",
     "legendFormat": "{{ endpoint }}-{{method}}-{{status}} [{{instance}}] "
    }
   ]
  },
  {
   "title": "Request size(bytes) per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(service_http_request_size_bytes_sum{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])\n/\nrate(service_http_request_size_bytes_count{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])",
     "legendFormat": "{{ endpoint }}-{{method}}-{{status}} [{{instance}}] "
    }
   ]
  },
  {
   "title": "Duration per request",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(service_http_request_duration_seconds_sum{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])\r\n/\r\nrate(service_http_request_duration_seconds_count{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])",
     "legendFormat": "{{ endpoint }}-{{method}}-{{status}}  [{{instance}}] "
    }
   ]
  },
  {
   "title": "Quantile of requests",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(service_http_request_duration_seconds_bucket{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])) by (le))",
     "legendFormat": "{{ endpoint }} "
    }
   ]
  },
  {
   "title": "Response size(bytes) per second",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(service_http_response_size_bytes_sum{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])\n/\nrate(service_http_response_size_bytes_count{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])",
     "legendFormat": "{{ endpoint }}-{{method}}-{{status}} [{{instance}}] "
    }
   ]
  }
 ]
}